
texts = {
    'en': {
        "app_title": "DNS Manager",
        "adapters_label": "Network Adapters",
        "dns_label": "DNS Profiles",
        "apply_button": "Apply DNS",
        "clear_button": "Clear DNS",
        "add_button": "Add DNS",
        "delete_button": "Delete DNS",
        "lang_button": "فارسی",
        "add_dns_title": "Add New DNS Profile",
        "add_dns_name": "Profile Name:",
        "add_dns_primary": "Primary DNS:",
        "add_dns_secondary": "Secondary DNS (optional):",
        "add_dns_save": "Save",
        "delete_dns_title": "Confirm Deletion",
        "delete_dns_confirm": "Are you sure you want to delete the selected DNS profile?",
        "success_title": "Success",
        "dns_set_success": "DNS applied successfully to the selected adapter.",
        "dns_cleared_success": "DNS cleared successfully for the selected adapter.",
        "error_title": "Error",
        "adapter_not_selected": "Please select a network adapter first.",
        "dns_not_selected": "Please select a DNS profile first."
    },
    'fa': {
        "app_title": "مدیریت DNS",
        "adapters_label": "کارت‌های شبکه",
        "dns_label": "پروفایل‌های DNS",
        "apply_button": "اعمال DNS",
        "clear_button": "پاک کردن DNS",
        "add_button": "افزودن DNS",
        "delete_button": "حذف DNS",
        "lang_button": "English",
        "add_dns_title": "افزودن پروفایل DNS جدید",
        "add_dns_name": "نام پروفایل:",
        "add_dns_primary": "DNS اصلی:",
        "add_dns_secondary": "DNS جایگزین (اختیاری):",
        "add_dns_save": "ذخیره",
        "delete_dns_title": "تایید حذف",
        "delete_dns_confirm": "آیا از حذف پروفایل DNS انتخاب شده مطمئن هستید؟",
        "success_title": "موفقیت",
        "dns_set_success": "DNS با موفقیت روی کارت شبکه انتخاب شده اعمال شد.",
        "dns_cleared_success": "DNS با موفقیت از روی کارت شبکه انتخاب شده پاک شد.",
        "error_title": "خطا",
        "adapter_not_selected": "لطفاً ابتدا یک کارت شبکه انتخاب کنید.",
        "dns_not_selected": "لطفاً ابتدا یک پروفایل DNS انتخاب کنید."
    }
}
